// Code generated by protoc-gen-go. DO NOT EDIT.
// source: build.proto

package contracts_v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Build_Corpus int32

const (
	Build_UNIVERSAL Build_Corpus = 0
	Build_WEB       Build_Corpus = 1
	Build_IMAGES    Build_Corpus = 2
	Build_LOCAL     Build_Corpus = 3
	Build_NEWS      Build_Corpus = 4
	Build_PRODUCTS  Build_Corpus = 5
	Build_VIDEO     Build_Corpus = 6
)

var Build_Corpus_name = map[int32]string{
	0: "UNIVERSAL",
	1: "WEB",
	2: "IMAGES",
	3: "LOCAL",
	4: "NEWS",
	5: "PRODUCTS",
	6: "VIDEO",
}

var Build_Corpus_value = map[string]int32{
	"UNIVERSAL": 0,
	"WEB":       1,
	"IMAGES":    2,
	"LOCAL":     3,
	"NEWS":      4,
	"PRODUCTS":  5,
	"VIDEO":     6,
}

func (x Build_Corpus) String() string {
	return proto.EnumName(Build_Corpus_name, int32(x))
}

func (Build_Corpus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_14ce178a580e4ede, []int{0, 0}
}

type Build struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RepoSource           string   `protobuf:"bytes,2,opt,name=repo_source,json=repoSource,proto3" json:"repo_source,omitempty"`
	RepoOwner            string   `protobuf:"bytes,3,opt,name=repo_owner,json=repoOwner,proto3" json:"repo_owner,omitempty"`
	RepoName             string   `protobuf:"bytes,4,opt,name=repo_name,json=repoName,proto3" json:"repo_name,omitempty"`
	RepoBranch           string   `protobuf:"bytes,5,opt,name=repo_branch,json=repoBranch,proto3" json:"repo_branch,omitempty"`
	RepoRevision         string   `protobuf:"bytes,6,opt,name=repo_revision,json=repoRevision,proto3" json:"repo_revision,omitempty"`
	BuildVersion         string   `protobuf:"bytes,7,opt,name=build_version,json=buildVersion,proto3" json:"build_version,omitempty"`
	BuildStatus          string   `protobuf:"bytes,8,opt,name=build_status,json=buildStatus,proto3" json:"build_status,omitempty"`
	Labels               []*Label `protobuf:"bytes,9,rep,name=labels,proto3" json:"labels,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Build) Reset()         { *m = Build{} }
func (m *Build) String() string { return proto.CompactTextString(m) }
func (*Build) ProtoMessage()    {}
func (*Build) Descriptor() ([]byte, []int) {
	return fileDescriptor_14ce178a580e4ede, []int{0}
}

func (m *Build) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Build.Unmarshal(m, b)
}
func (m *Build) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Build.Marshal(b, m, deterministic)
}
func (m *Build) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Build.Merge(m, src)
}
func (m *Build) XXX_Size() int {
	return xxx_messageInfo_Build.Size(m)
}
func (m *Build) XXX_DiscardUnknown() {
	xxx_messageInfo_Build.DiscardUnknown(m)
}

var xxx_messageInfo_Build proto.InternalMessageInfo

func (m *Build) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Build) GetRepoSource() string {
	if m != nil {
		return m.RepoSource
	}
	return ""
}

func (m *Build) GetRepoOwner() string {
	if m != nil {
		return m.RepoOwner
	}
	return ""
}

func (m *Build) GetRepoName() string {
	if m != nil {
		return m.RepoName
	}
	return ""
}

func (m *Build) GetRepoBranch() string {
	if m != nil {
		return m.RepoBranch
	}
	return ""
}

func (m *Build) GetRepoRevision() string {
	if m != nil {
		return m.RepoRevision
	}
	return ""
}

func (m *Build) GetBuildVersion() string {
	if m != nil {
		return m.BuildVersion
	}
	return ""
}

func (m *Build) GetBuildStatus() string {
	if m != nil {
		return m.BuildStatus
	}
	return ""
}

func (m *Build) GetLabels() []*Label {
	if m != nil {
		return m.Labels
	}
	return nil
}

func init() {
	proto.RegisterEnum("contracts.v1.Build_Corpus", Build_Corpus_name, Build_Corpus_value)
	proto.RegisterType((*Build)(nil), "contracts.v1.Build")
}

func init() { proto.RegisterFile("build.proto", fileDescriptor_14ce178a580e4ede) }

var fileDescriptor_14ce178a580e4ede = []byte{
	// 324 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x91, 0xdf, 0x6a, 0xa3, 0x40,
	0x14, 0xc6, 0x37, 0x1a, 0x8d, 0x1e, 0x93, 0x45, 0xce, 0xde, 0x0c, 0xbb, 0x2c, 0x4d, 0xd3, 0x9b,
	0x40, 0x41, 0x68, 0xfb, 0x04, 0xf9, 0x23, 0x25, 0x60, 0x63, 0xd1, 0x26, 0x81, 0xde, 0x88, 0x9a,
	0x81, 0x0a, 0x89, 0x13, 0x66, 0x34, 0x7d, 0x88, 0xbe, 0x74, 0x99, 0x63, 0x68, 0x7b, 0xf9, 0xfd,
	0xbe, 0x1f, 0x07, 0xe6, 0x1b, 0xf0, 0x8a, 0xb6, 0x3a, 0xec, 0x83, 0x93, 0x14, 0x8d, 0xc0, 0x61,
	0x29, 0xea, 0x46, 0xe6, 0x65, 0xa3, 0x82, 0xf3, 0xdd, 0x5f, 0xef, 0x90, 0x17, 0xfc, 0xd0, 0x55,
	0x93, 0x0f, 0x13, 0xac, 0xb9, 0x56, 0xf1, 0x37, 0x18, 0xd5, 0x9e, 0xf5, 0xc6, 0xbd, 0xa9, 0x9b,
	0x18, 0xd5, 0x1e, 0xaf, 0xc0, 0x93, 0xfc, 0x24, 0x32, 0x25, 0x5a, 0x59, 0x72, 0x66, 0x50, 0x01,
	0x1a, 0xa5, 0x44, 0xf0, 0x3f, 0x50, 0xca, 0xc4, 0x7b, 0xcd, 0x25, 0x33, 0xa9, 0x77, 0x35, 0x89,
	0x35, 0xc0, 0x7f, 0x40, 0x21, 0xab, 0xf3, 0x23, 0x67, 0x7d, 0x6a, 0x1d, 0x0d, 0xd6, 0xf9, 0x91,
	0x7f, 0x1d, 0x2f, 0x64, 0x5e, 0x97, 0x6f, 0xcc, 0xfa, 0x3e, 0x3e, 0x27, 0x82, 0x37, 0x30, 0x22,
	0x41, 0xf2, 0x73, 0xa5, 0x2a, 0x51, 0x33, 0x9b, 0x94, 0xa1, 0x86, 0xc9, 0x85, 0x69, 0x89, 0x9e,
	0x99, 0x9d, 0xb9, 0x24, 0x69, 0xd0, 0x49, 0x04, 0xb7, 0x1d, 0xc3, 0x6b, 0xe8, 0x72, 0xa6, 0x9a,
	0xbc, 0x69, 0x15, 0x73, 0xc8, 0xe9, 0xf6, 0x49, 0x09, 0xe1, 0x2d, 0xd8, 0xb4, 0x89, 0x62, 0xee,
	0xd8, 0x9c, 0x7a, 0xf7, 0x7f, 0x82, 0x9f, 0x83, 0x05, 0x91, 0xee, 0x92, 0x8b, 0x32, 0x79, 0x05,
	0x7b, 0x21, 0xe4, 0xa9, 0x55, 0x38, 0x02, 0x77, 0xb3, 0x5e, 0x6d, 0xc3, 0x24, 0x9d, 0x45, 0xfe,
	0x2f, 0x1c, 0x80, 0xb9, 0x0b, 0xe7, 0x7e, 0x0f, 0x01, 0xec, 0xd5, 0xd3, 0xec, 0x31, 0x4c, 0x7d,
	0x03, 0x5d, 0xb0, 0xa2, 0x78, 0x31, 0x8b, 0x7c, 0x13, 0x1d, 0xe8, 0xaf, 0xc3, 0x5d, 0xea, 0xf7,
	0x71, 0x08, 0xce, 0x73, 0x12, 0x2f, 0x37, 0x8b, 0x97, 0xd4, 0xb7, 0xb4, 0xb2, 0x5d, 0x2d, 0xc3,
	0xd8, 0xb7, 0x0b, 0x9b, 0x3e, 0xe5, 0xe1, 0x33, 0x00, 0x00, 0xff, 0xff, 0xca, 0xf3, 0x0f, 0xb8,
	0xbe, 0x01, 0x00, 0x00,
}
