// Code generated by protoc-gen-go. DO NOT EDIT.
// source: build.proto

package contracts

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Build struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RepoSource           string   `protobuf:"bytes,2,opt,name=repo_source,json=repoSource,proto3" json:"repo_source,omitempty"`
	RepoOwner            string   `protobuf:"bytes,3,opt,name=repo_owner,json=repoOwner,proto3" json:"repo_owner,omitempty"`
	RepoName             string   `protobuf:"bytes,4,opt,name=repo_name,json=repoName,proto3" json:"repo_name,omitempty"`
	RepoBranch           string   `protobuf:"bytes,5,opt,name=repo_branch,json=repoBranch,proto3" json:"repo_branch,omitempty"`
	RepoRevision         string   `protobuf:"bytes,6,opt,name=repo_revision,json=repoRevision,proto3" json:"repo_revision,omitempty"`
	BuildVersion         string   `protobuf:"bytes,7,opt,name=build_version,json=buildVersion,proto3" json:"build_version,omitempty"`
	BuildStatus          string   `protobuf:"bytes,8,opt,name=build_status,json=buildStatus,proto3" json:"build_status,omitempty"`
	Labels               []*Label `protobuf:"bytes,9,rep,name=labels,proto3" json:"labels,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Build) Reset()         { *m = Build{} }
func (m *Build) String() string { return proto.CompactTextString(m) }
func (*Build) ProtoMessage()    {}
func (*Build) Descriptor() ([]byte, []int) {
	return fileDescriptor_14ce178a580e4ede, []int{0}
}

func (m *Build) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Build.Unmarshal(m, b)
}
func (m *Build) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Build.Marshal(b, m, deterministic)
}
func (m *Build) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Build.Merge(m, src)
}
func (m *Build) XXX_Size() int {
	return xxx_messageInfo_Build.Size(m)
}
func (m *Build) XXX_DiscardUnknown() {
	xxx_messageInfo_Build.DiscardUnknown(m)
}

var xxx_messageInfo_Build proto.InternalMessageInfo

func (m *Build) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Build) GetRepoSource() string {
	if m != nil {
		return m.RepoSource
	}
	return ""
}

func (m *Build) GetRepoOwner() string {
	if m != nil {
		return m.RepoOwner
	}
	return ""
}

func (m *Build) GetRepoName() string {
	if m != nil {
		return m.RepoName
	}
	return ""
}

func (m *Build) GetRepoBranch() string {
	if m != nil {
		return m.RepoBranch
	}
	return ""
}

func (m *Build) GetRepoRevision() string {
	if m != nil {
		return m.RepoRevision
	}
	return ""
}

func (m *Build) GetBuildVersion() string {
	if m != nil {
		return m.BuildVersion
	}
	return ""
}

func (m *Build) GetBuildStatus() string {
	if m != nil {
		return m.BuildStatus
	}
	return ""
}

func (m *Build) GetLabels() []*Label {
	if m != nil {
		return m.Labels
	}
	return nil
}

func init() {
	proto.RegisterType((*Build)(nil), "contracts.Build")
}

func init() { proto.RegisterFile("build.proto", fileDescriptor_14ce178a580e4ede) }

var fileDescriptor_14ce178a580e4ede = []byte{
	// 239 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x90, 0x51, 0x4b, 0xc3, 0x30,
	0x14, 0x85, 0x59, 0xe7, 0xea, 0x7a, 0xab, 0x22, 0x79, 0x0a, 0x8a, 0x38, 0xf5, 0xa5, 0x4f, 0x7d,
	0xd0, 0x7f, 0xb0, 0x67, 0x51, 0xe8, 0xc0, 0xd7, 0x90, 0xb6, 0x01, 0x03, 0x5d, 0x32, 0x92, 0x74,
	0xfe, 0x29, 0x7f, 0xa4, 0xdc, 0x93, 0x31, 0x1f, 0xcf, 0x77, 0x3e, 0x2e, 0xdc, 0x43, 0x75, 0x3f,
	0xdb, 0x69, 0x6c, 0x0f, 0xc1, 0x27, 0x2f, 0xaa, 0xc1, 0xbb, 0x14, 0xf4, 0x90, 0xe2, 0x5d, 0x3d,
	0xe9, 0xde, 0x4c, 0x99, 0x3f, 0xff, 0x16, 0xb4, 0xda, 0xb2, 0x27, 0x6e, 0xa8, 0xb0, 0xa3, 0x5c,
	0x6c, 0x16, 0x4d, 0xd5, 0x15, 0x76, 0x14, 0x8f, 0x54, 0x07, 0x73, 0xf0, 0x2a, 0xfa, 0x39, 0x0c,
	0x46, 0x16, 0x28, 0x88, 0xd1, 0x0e, 0x44, 0x3c, 0x10, 0x92, 0xf2, 0x3f, 0xce, 0x04, 0xb9, 0x44,
	0x5f, 0x31, 0xf9, 0x64, 0x20, 0xee, 0x09, 0x41, 0x39, 0xbd, 0x37, 0xf2, 0x02, 0xed, 0x9a, 0xc1,
	0x87, 0xde, 0x9b, 0xf3, 0xf1, 0x3e, 0x68, 0x37, 0x7c, 0xcb, 0xd5, 0xff, 0xf1, 0x2d, 0x88, 0x78,
	0xa1, 0x6b, 0x08, 0xc1, 0x1c, 0x6d, 0xb4, 0xde, 0xc9, 0x12, 0xca, 0x15, 0xc3, 0xee, 0xc4, 0x58,
	0xc2, 0x8f, 0xea, 0x68, 0x02, 0xa4, 0xcb, 0x2c, 0x01, 0x7e, 0x65, 0x26, 0x9e, 0x28, 0x67, 0x15,
	0x93, 0x4e, 0x73, 0x94, 0x6b, 0x38, 0x79, 0x9c, 0x1d, 0x90, 0x68, 0xa8, 0xc4, 0x26, 0x51, 0x56,
	0x9b, 0x65, 0x53, 0xbf, 0xde, 0xb6, 0xe7, 0xb5, 0xda, 0x77, 0x2e, 0xba, 0x53, 0xdf, 0x97, 0x58,
	0xed, 0xed, 0x2f, 0x00, 0x00, 0xff, 0xff, 0xac, 0x8c, 0x50, 0x45, 0x5c, 0x01, 0x00, 0x00,
}
