// Code generated by protoc-gen-go. DO NOT EDIT.
// source: contracts.v1/build_version_config.proto

package contracts_v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BuildVersionConfig struct {
	Version              string   `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Major                int64    `protobuf:"varint,2,opt,name=major,proto3" json:"major,omitempty"`
	Minor                int64    `protobuf:"varint,3,opt,name=minor,proto3" json:"minor,omitempty"`
	Patch                string   `protobuf:"bytes,4,opt,name=patch,proto3" json:"patch,omitempty"`
	Label                string   `protobuf:"bytes,5,opt,name=label,proto3" json:"label,omitempty"`
	AutoIncrement        int64    `protobuf:"varint,6,opt,name=auto_increment,json=autoIncrement,proto3" json:"auto_increment,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BuildVersionConfig) Reset()         { *m = BuildVersionConfig{} }
func (m *BuildVersionConfig) String() string { return proto.CompactTextString(m) }
func (*BuildVersionConfig) ProtoMessage()    {}
func (*BuildVersionConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_bdd2ac76605caf77, []int{0}
}

func (m *BuildVersionConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuildVersionConfig.Unmarshal(m, b)
}
func (m *BuildVersionConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuildVersionConfig.Marshal(b, m, deterministic)
}
func (m *BuildVersionConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuildVersionConfig.Merge(m, src)
}
func (m *BuildVersionConfig) XXX_Size() int {
	return xxx_messageInfo_BuildVersionConfig.Size(m)
}
func (m *BuildVersionConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_BuildVersionConfig.DiscardUnknown(m)
}

var xxx_messageInfo_BuildVersionConfig proto.InternalMessageInfo

func (m *BuildVersionConfig) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *BuildVersionConfig) GetMajor() int64 {
	if m != nil {
		return m.Major
	}
	return 0
}

func (m *BuildVersionConfig) GetMinor() int64 {
	if m != nil {
		return m.Minor
	}
	return 0
}

func (m *BuildVersionConfig) GetPatch() string {
	if m != nil {
		return m.Patch
	}
	return ""
}

func (m *BuildVersionConfig) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

func (m *BuildVersionConfig) GetAutoIncrement() int64 {
	if m != nil {
		return m.AutoIncrement
	}
	return 0
}

func init() {
	proto.RegisterType((*BuildVersionConfig)(nil), "contracts.v1.BuildVersionConfig")
}

func init() {
	proto.RegisterFile("contracts.v1/build_version_config.proto", fileDescriptor_bdd2ac76605caf77)
}

var fileDescriptor_bdd2ac76605caf77 = []byte{
	// 224 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0xb1, 0x4e, 0xc4, 0x20,
	0x1c, 0x87, 0x83, 0xe7, 0x9d, 0x91, 0xa8, 0x03, 0x71, 0x60, 0xbc, 0x98, 0x18, 0x6f, 0x69, 0x9b,
	0x8b, 0x0f, 0x60, 0x3c, 0x27, 0xd7, 0x1b, 0x1c, 0x5c, 0x08, 0x20, 0xc7, 0x61, 0x28, 0xff, 0x86,
	0xfe, 0xdb, 0xb7, 0xf2, 0x1d, 0x0d, 0xd0, 0x56, 0x37, 0xbe, 0x2f, 0x1f, 0xbf, 0x04, 0xe8, 0x93,
	0x86, 0x80, 0x51, 0x6a, 0xec, 0xeb, 0x71, 0xdf, 0xa8, 0xc1, 0xf9, 0x2f, 0x31, 0x9a, 0xd8, 0x3b,
	0x08, 0x42, 0x43, 0x38, 0x39, 0x5b, 0x77, 0x11, 0x10, 0xd8, 0xcd, 0xff, 0xf0, 0xe1, 0x87, 0x50,
	0x76, 0x48, 0xf1, 0x47, 0x69, 0xdf, 0x72, 0xca, 0x38, 0xbd, 0x9a, 0x2e, 0x73, 0xb2, 0x25, 0xbb,
	0xeb, 0xe3, 0x8c, 0xec, 0x9e, 0xae, 0x5b, 0xf9, 0x0d, 0x91, 0x5f, 0x6c, 0xc9, 0x6e, 0x75, 0x2c,
	0x90, 0xad, 0x0b, 0x10, 0xf9, 0x6a, 0xb2, 0x09, 0x92, 0xed, 0x24, 0xea, 0x33, 0xbf, 0xcc, 0x1b,
	0x05, 0x92, 0xf5, 0x52, 0x19, 0xcf, 0xd7, 0xc5, 0x66, 0x60, 0x8f, 0xf4, 0x4e, 0x0e, 0x08, 0xc2,
	0x05, 0x1d, 0x4d, 0x6b, 0x02, 0xf2, 0x4d, 0x9e, 0xba, 0x4d, 0xf6, 0x7d, 0x96, 0x87, 0xd7, 0xcf,
	0x17, 0xeb, 0xf0, 0x3c, 0xa8, 0x5a, 0x43, 0xdb, 0x98, 0x1e, 0xe5, 0xc9, 0x20, 0x9a, 0xbf, 0x53,
	0xa5, 0x5d, 0xb5, 0xbc, 0xb0, 0xb2, 0xe0, 0x65, 0xb0, 0xcd, 0x22, 0xc4, 0xb8, 0x57, 0x9b, 0xfc,
	0x0f, 0xcf, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x7f, 0x2d, 0xa0, 0x6d, 0x32, 0x01, 0x00, 0x00,
}
