// Code generated by protoc-gen-go. DO NOT EDIT.
// source: contracts.v1/container_repository_credential_config.proto

package contracts_v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ContainerRepositoryCredentialConfig struct {
	Repository           string   `protobuf:"bytes,1,opt,name=repository,proto3" json:"repository,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ContainerRepositoryCredentialConfig) Reset()         { *m = ContainerRepositoryCredentialConfig{} }
func (m *ContainerRepositoryCredentialConfig) String() string { return proto.CompactTextString(m) }
func (*ContainerRepositoryCredentialConfig) ProtoMessage()    {}
func (*ContainerRepositoryCredentialConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_befed981f1adee4e, []int{0}
}

func (m *ContainerRepositoryCredentialConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContainerRepositoryCredentialConfig.Unmarshal(m, b)
}
func (m *ContainerRepositoryCredentialConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContainerRepositoryCredentialConfig.Marshal(b, m, deterministic)
}
func (m *ContainerRepositoryCredentialConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContainerRepositoryCredentialConfig.Merge(m, src)
}
func (m *ContainerRepositoryCredentialConfig) XXX_Size() int {
	return xxx_messageInfo_ContainerRepositoryCredentialConfig.Size(m)
}
func (m *ContainerRepositoryCredentialConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_ContainerRepositoryCredentialConfig.DiscardUnknown(m)
}

var xxx_messageInfo_ContainerRepositoryCredentialConfig proto.InternalMessageInfo

func (m *ContainerRepositoryCredentialConfig) GetRepository() string {
	if m != nil {
		return m.Repository
	}
	return ""
}

func (m *ContainerRepositoryCredentialConfig) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *ContainerRepositoryCredentialConfig) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func init() {
	proto.RegisterType((*ContainerRepositoryCredentialConfig)(nil), "contracts.v1.ContainerRepositoryCredentialConfig")
}

func init() {
	proto.RegisterFile("contracts.v1/container_repository_credential_config.proto", fileDescriptor_befed981f1adee4e)
}

var fileDescriptor_befed981f1adee4e = []byte{
	// 225 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x8f, 0xb1, 0x4a, 0x04, 0x31,
	0x10, 0x86, 0xb9, 0x13, 0x44, 0x83, 0xd5, 0x56, 0xab, 0x88, 0x88, 0x36, 0x36, 0x9b, 0x65, 0xb1,
	0x12, 0xac, 0x0c, 0x16, 0xb6, 0x57, 0x58, 0xd8, 0x84, 0x5c, 0x6e, 0x2e, 0x0e, 0xdc, 0x65, 0x96,
	0xc9, 0xdc, 0xa9, 0x85, 0x2f, 0xe4, 0x53, 0xca, 0xe5, 0xd8, 0xec, 0x76, 0xf9, 0xf3, 0xcf, 0xf7,
	0x31, 0xa3, 0x9e, 0x3c, 0x45, 0x61, 0xe7, 0x25, 0xe9, 0x7d, 0xd7, 0x1e, 0x82, 0xc3, 0x08, 0x6c,
	0x19, 0x7a, 0x4a, 0x28, 0xc4, 0x3f, 0xd6, 0x33, 0xac, 0x20, 0x0a, 0xba, 0x8d, 0xf5, 0x14, 0xd7,
	0x18, 0x74, 0xcf, 0x24, 0x54, 0x5d, 0x4c, 0xd1, 0xbb, 0x5f, 0x75, 0x6f, 0x06, 0x7a, 0x51, 0x60,
	0x53, 0x58, 0x93, 0xd1, 0xea, 0x46, 0xa9, 0x51, 0x5d, 0xcf, 0x6e, 0x67, 0x0f, 0xe7, 0x8b, 0xc9,
	0x4f, 0x75, 0xa5, 0xce, 0x76, 0x09, 0x38, 0xba, 0x2d, 0xd4, 0xf3, 0xdc, 0x96, 0x7c, 0xe8, 0x7a,
	0x97, 0xd2, 0x17, 0xf1, 0xaa, 0x3e, 0x39, 0x76, 0x43, 0x7e, 0xf9, 0x56, 0xd7, 0x48, 0x1a, 0x92,
	0xb8, 0x35, 0x88, 0x80, 0xf6, 0xa8, 0xa7, 0xeb, 0x7d, 0x3c, 0x07, 0x94, 0xcf, 0xdd, 0x52, 0x7b,
	0xda, 0xb6, 0x65, 0x6a, 0x7c, 0x35, 0x1e, 0x9b, 0x7c, 0x55, 0x6a, 0x02, 0x6d, 0x5c, 0x0c, 0x6d,
	0xa1, 0xed, 0xbe, 0xfb, 0x9b, 0x5f, 0xbe, 0x16, 0xb3, 0x79, 0xd3, 0xa6, 0x98, 0xdf, 0xbb, 0xe5,
	0x69, 0xe6, 0x1e, 0xff, 0x03, 0x00, 0x00, 0xff, 0xff, 0x31, 0x68, 0x5b, 0x01, 0x4a, 0x01, 0x00,
	0x00,
}
