// Code generated by protoc-gen-go. DO NOT EDIT.
// source: contracts.v1/pagination.proto

package contracts_v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Pagination struct {
	Page                 int64    `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size                 int64    `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	TotalPages           int64    `protobuf:"varint,3,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`
	TotalItems           int64    `protobuf:"varint,4,opt,name=total_items,json=totalItems,proto3" json:"total_items,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pagination) Reset()         { *m = Pagination{} }
func (m *Pagination) String() string { return proto.CompactTextString(m) }
func (*Pagination) ProtoMessage()    {}
func (*Pagination) Descriptor() ([]byte, []int) {
	return fileDescriptor_df7053f4f8fa7581, []int{0}
}

func (m *Pagination) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pagination.Unmarshal(m, b)
}
func (m *Pagination) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pagination.Marshal(b, m, deterministic)
}
func (m *Pagination) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pagination.Merge(m, src)
}
func (m *Pagination) XXX_Size() int {
	return xxx_messageInfo_Pagination.Size(m)
}
func (m *Pagination) XXX_DiscardUnknown() {
	xxx_messageInfo_Pagination.DiscardUnknown(m)
}

var xxx_messageInfo_Pagination proto.InternalMessageInfo

func (m *Pagination) GetPage() int64 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *Pagination) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *Pagination) GetTotalPages() int64 {
	if m != nil {
		return m.TotalPages
	}
	return 0
}

func (m *Pagination) GetTotalItems() int64 {
	if m != nil {
		return m.TotalItems
	}
	return 0
}

func init() {
	proto.RegisterType((*Pagination)(nil), "contracts.v1.Pagination")
}

func init() { proto.RegisterFile("contracts.v1/pagination.proto", fileDescriptor_df7053f4f8fa7581) }

var fileDescriptor_df7053f4f8fa7581 = []byte{
	// 178 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x8f, 0x31, 0x0f, 0x82, 0x30,
	0x10, 0x46, 0x83, 0x10, 0x87, 0xea, 0xd4, 0xa9, 0x8b, 0xd1, 0x38, 0xb9, 0x00, 0x21, 0xfe, 0x00,
	0xa3, 0x9b, 0x1b, 0x71, 0x74, 0x21, 0x47, 0x53, 0x6b, 0x13, 0xe8, 0x11, 0x7a, 0x32, 0xf8, 0xeb,
	0x4d, 0x6b, 0x52, 0xd8, 0x5e, 0xde, 0xf7, 0x86, 0x3b, 0xb6, 0x93, 0x68, 0x69, 0x04, 0x49, 0xae,
	0x98, 0xaa, 0x72, 0x00, 0x6d, 0x2c, 0x90, 0x41, 0x5b, 0x0c, 0x23, 0x12, 0xf2, 0xed, 0x72, 0x3e,
	0x4e, 0x8c, 0xd5, 0xb1, 0xe0, 0x9c, 0x65, 0x03, 0x68, 0x25, 0x92, 0x43, 0x72, 0x4a, 0x1f, 0x81,
	0xbd, 0x73, 0xe6, 0xab, 0xc4, 0xea, 0xef, 0x3c, 0xf3, 0x3d, 0xdb, 0x10, 0x12, 0x74, 0x8d, 0x2f,
	0x9c, 0x48, 0xc3, 0xc4, 0x82, 0xaa, 0xbd, 0x99, 0x03, 0x43, 0xaa, 0x77, 0x22, 0x5b, 0x04, 0x77,
	0x6f, 0x6e, 0xd7, 0xe7, 0x45, 0x1b, 0x7a, 0x7f, 0xda, 0x42, 0x62, 0x5f, 0x2a, 0x47, 0xf0, 0x52,
	0x44, 0x6a, 0xa6, 0x5c, 0x9a, 0x3c, 0x5e, 0x9a, 0x6b, 0xec, 0xc0, 0xea, 0x32, 0x8a, 0x66, 0xaa,
	0xda, 0x75, 0xf8, 0xe7, 0xfc, 0x0b, 0x00, 0x00, 0xff, 0xff, 0x8f, 0xa7, 0x32, 0x80, 0xf0, 0x00,
	0x00, 0x00,
}
