// Code generated by protoc-gen-go. DO NOT EDIT.
// source: contracts.v1/release_params_config.proto

package contracts_v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ReleaseParamsConfig struct {
	ReleaseName          string   `protobuf:"bytes,1,opt,name=release_name,json=releaseName,proto3" json:"release_name,omitempty"`
	ReleaseId            int64    `protobuf:"varint,2,opt,name=release_id,json=releaseId,proto3" json:"release_id,omitempty"`
	ReleaseAction        string   `protobuf:"bytes,3,opt,name=release_action,json=releaseAction,proto3" json:"release_action,omitempty"`
	TriggeredBy          string   `protobuf:"bytes,4,opt,name=triggered_by,json=triggeredBy,proto3" json:"triggered_by,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReleaseParamsConfig) Reset()         { *m = ReleaseParamsConfig{} }
func (m *ReleaseParamsConfig) String() string { return proto.CompactTextString(m) }
func (*ReleaseParamsConfig) ProtoMessage()    {}
func (*ReleaseParamsConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fbde7c48653f2c6, []int{0}
}

func (m *ReleaseParamsConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReleaseParamsConfig.Unmarshal(m, b)
}
func (m *ReleaseParamsConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReleaseParamsConfig.Marshal(b, m, deterministic)
}
func (m *ReleaseParamsConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReleaseParamsConfig.Merge(m, src)
}
func (m *ReleaseParamsConfig) XXX_Size() int {
	return xxx_messageInfo_ReleaseParamsConfig.Size(m)
}
func (m *ReleaseParamsConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_ReleaseParamsConfig.DiscardUnknown(m)
}

var xxx_messageInfo_ReleaseParamsConfig proto.InternalMessageInfo

func (m *ReleaseParamsConfig) GetReleaseName() string {
	if m != nil {
		return m.ReleaseName
	}
	return ""
}

func (m *ReleaseParamsConfig) GetReleaseId() int64 {
	if m != nil {
		return m.ReleaseId
	}
	return 0
}

func (m *ReleaseParamsConfig) GetReleaseAction() string {
	if m != nil {
		return m.ReleaseAction
	}
	return ""
}

func (m *ReleaseParamsConfig) GetTriggeredBy() string {
	if m != nil {
		return m.TriggeredBy
	}
	return ""
}

func init() {
	proto.RegisterType((*ReleaseParamsConfig)(nil), "contracts.v1.ReleaseParamsConfig")
}

func init() {
	proto.RegisterFile("contracts.v1/release_params_config.proto", fileDescriptor_2fbde7c48653f2c6)
}

var fileDescriptor_2fbde7c48653f2c6 = []byte{
	// 221 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x8f, 0xcd, 0x4a, 0x03, 0x31,
	0x14, 0x85, 0x89, 0x15, 0xa1, 0xb1, 0xba, 0x88, 0x9b, 0x6c, 0x84, 0x2a, 0x08, 0xb3, 0x99, 0x19,
	0x8a, 0x0f, 0x20, 0xad, 0x2b, 0x37, 0x22, 0xb3, 0x74, 0x13, 0xee, 0x64, 0x6e, 0x63, 0xa0, 0x49,
	0x4a, 0x72, 0x2d, 0xcc, 0xe3, 0xf8, 0xa6, 0x62, 0xe6, 0xc7, 0xee, 0x2e, 0xdf, 0xfd, 0x38, 0x87,
	0xc3, 0x0b, 0x1d, 0x3c, 0x45, 0xd0, 0x94, 0xaa, 0xd3, 0xa6, 0x8e, 0x78, 0x40, 0x48, 0xa8, 0x8e,
	0x10, 0xc1, 0x25, 0xa5, 0x83, 0xdf, 0x5b, 0x53, 0x1d, 0x63, 0xa0, 0x20, 0x56, 0xe7, 0xe6, 0xe3,
	0x0f, 0xe3, 0x77, 0xcd, 0x60, 0x7f, 0x64, 0xf9, 0x35, 0xbb, 0xe2, 0x81, 0xaf, 0xa6, 0x10, 0x0f,
	0x0e, 0x25, 0x5b, 0xb3, 0x62, 0xd9, 0x5c, 0x8f, 0xec, 0x1d, 0x1c, 0x8a, 0x7b, 0xce, 0x27, 0xc5,
	0x76, 0xf2, 0x62, 0xcd, 0x8a, 0x45, 0xb3, 0x1c, 0xc9, 0x5b, 0x27, 0x9e, 0xf8, 0xed, 0xf4, 0x06,
	0x4d, 0x36, 0x78, 0xb9, 0xc8, 0x19, 0x37, 0x23, 0xdd, 0x66, 0xf8, 0x57, 0x44, 0xd1, 0x1a, 0x83,
	0x11, 0x3b, 0xd5, 0xf6, 0xf2, 0x72, 0x28, 0x9a, 0xd9, 0xae, 0xdf, 0x6d, 0x3f, 0x5f, 0x8c, 0xa5,
	0xaf, 0xef, 0xb6, 0xd2, 0xc1, 0xd5, 0x98, 0x08, 0xf6, 0x48, 0x84, 0xff, 0x57, 0xa9, 0x6d, 0x39,
	0xaf, 0x2a, 0x4d, 0x38, 0x80, 0x37, 0xf5, 0x0c, 0xd4, 0x69, 0xd3, 0x5e, 0xe5, 0xed, 0xcf, 0xbf,
	0x01, 0x00, 0x00, 0xff, 0xff, 0x0e, 0x19, 0x6e, 0x6e, 0x27, 0x01, 0x00, 0x00,
}
