// Code generated by protoc-gen-go. DO NOT EDIT.
// source: manifest.v1/estafette_release_action.proto

package manifest_v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EstafetteReleaseAction struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EstafetteReleaseAction) Reset()         { *m = EstafetteReleaseAction{} }
func (m *EstafetteReleaseAction) String() string { return proto.CompactTextString(m) }
func (*EstafetteReleaseAction) ProtoMessage()    {}
func (*EstafetteReleaseAction) Descriptor() ([]byte, []int) {
	return fileDescriptor_3071f2fabe9c194c, []int{0}
}

func (m *EstafetteReleaseAction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EstafetteReleaseAction.Unmarshal(m, b)
}
func (m *EstafetteReleaseAction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EstafetteReleaseAction.Marshal(b, m, deterministic)
}
func (m *EstafetteReleaseAction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EstafetteReleaseAction.Merge(m, src)
}
func (m *EstafetteReleaseAction) XXX_Size() int {
	return xxx_messageInfo_EstafetteReleaseAction.Size(m)
}
func (m *EstafetteReleaseAction) XXX_DiscardUnknown() {
	xxx_messageInfo_EstafetteReleaseAction.DiscardUnknown(m)
}

var xxx_messageInfo_EstafetteReleaseAction proto.InternalMessageInfo

func (m *EstafetteReleaseAction) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*EstafetteReleaseAction)(nil), "manifest.v1.EstafetteReleaseAction")
}

func init() {
	proto.RegisterFile("manifest.v1/estafette_release_action.proto", fileDescriptor_3071f2fabe9c194c)
}

var fileDescriptor_3071f2fabe9c194c = []byte{
	// 151 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xd2, 0xca, 0x4d, 0xcc, 0xcb,
	0x4c, 0x4b, 0x2d, 0x2e, 0xd1, 0x2b, 0x33, 0xd4, 0x4f, 0x2d, 0x2e, 0x49, 0x4c, 0x4b, 0x2d, 0x29,
	0x49, 0x8d, 0x2f, 0x4a, 0xcd, 0x49, 0x4d, 0x2c, 0x4e, 0x8d, 0x4f, 0x4c, 0x2e, 0xc9, 0xcc, 0xcf,
	0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x46, 0x52, 0xab, 0xa4, 0xc3, 0x25, 0xe6, 0x0a,
	0x53, 0x1e, 0x04, 0x51, 0xed, 0x08, 0x56, 0x2c, 0x24, 0xc4, 0xc5, 0x92, 0x97, 0x98, 0x9b, 0x2a,
	0xc1, 0xa8, 0xc0, 0xa8, 0xc1, 0x19, 0x04, 0x66, 0x3b, 0x39, 0x44, 0xd9, 0xa5, 0x67, 0x96, 0x64,
	0x94, 0x26, 0xe9, 0x25, 0xe7, 0xe7, 0x22, 0xec, 0x41, 0xb0, 0x74, 0x93, 0x33, 0x75, 0x93, 0xf3,
	0xf3, 0x4a, 0x8a, 0x12, 0x93, 0x4b, 0x8a, 0x75, 0xd3, 0xf3, 0x73, 0x12, 0xf3, 0xd2, 0xf5, 0x61,
	0xf6, 0xc5, 0x97, 0x19, 0x26, 0xb1, 0x81, 0xdd, 0x60, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0xd8,
	0x6c, 0x79, 0xfe, 0xb1, 0x00, 0x00, 0x00,
}
