// Code generated by protoc-gen-go. DO NOT EDIT.
// source: manifest.v1/estafette_pipeline_event.proto

package manifest_v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EstafettePipelineEvent struct {
	BuildVersion         string   `protobuf:"bytes,1,opt,name=build_version,json=buildVersion,proto3" json:"build_version,omitempty"`
	RepoSource           string   `protobuf:"bytes,2,opt,name=repo_source,json=repoSource,proto3" json:"repo_source,omitempty"`
	RepoOwner            string   `protobuf:"bytes,3,opt,name=repo_owner,json=repoOwner,proto3" json:"repo_owner,omitempty"`
	RepoName             string   `protobuf:"bytes,4,opt,name=repo_name,json=repoName,proto3" json:"repo_name,omitempty"`
	RepoBranch           string   `protobuf:"bytes,5,opt,name=repo_branch,json=repoBranch,proto3" json:"repo_branch,omitempty"`
	Status               string   `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	Event                string   `protobuf:"bytes,7,opt,name=event,proto3" json:"event,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EstafettePipelineEvent) Reset()         { *m = EstafettePipelineEvent{} }
func (m *EstafettePipelineEvent) String() string { return proto.CompactTextString(m) }
func (*EstafettePipelineEvent) ProtoMessage()    {}
func (*EstafettePipelineEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0cd8e4dfb4a4d7e, []int{0}
}

func (m *EstafettePipelineEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EstafettePipelineEvent.Unmarshal(m, b)
}
func (m *EstafettePipelineEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EstafettePipelineEvent.Marshal(b, m, deterministic)
}
func (m *EstafettePipelineEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EstafettePipelineEvent.Merge(m, src)
}
func (m *EstafettePipelineEvent) XXX_Size() int {
	return xxx_messageInfo_EstafettePipelineEvent.Size(m)
}
func (m *EstafettePipelineEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_EstafettePipelineEvent.DiscardUnknown(m)
}

var xxx_messageInfo_EstafettePipelineEvent proto.InternalMessageInfo

func (m *EstafettePipelineEvent) GetBuildVersion() string {
	if m != nil {
		return m.BuildVersion
	}
	return ""
}

func (m *EstafettePipelineEvent) GetRepoSource() string {
	if m != nil {
		return m.RepoSource
	}
	return ""
}

func (m *EstafettePipelineEvent) GetRepoOwner() string {
	if m != nil {
		return m.RepoOwner
	}
	return ""
}

func (m *EstafettePipelineEvent) GetRepoName() string {
	if m != nil {
		return m.RepoName
	}
	return ""
}

func (m *EstafettePipelineEvent) GetRepoBranch() string {
	if m != nil {
		return m.RepoBranch
	}
	return ""
}

func (m *EstafettePipelineEvent) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *EstafettePipelineEvent) GetEvent() string {
	if m != nil {
		return m.Event
	}
	return ""
}

func init() {
	proto.RegisterType((*EstafettePipelineEvent)(nil), "manifest.v1.EstafettePipelineEvent")
}

func init() {
	proto.RegisterFile("manifest.v1/estafette_pipeline_event.proto", fileDescriptor_e0cd8e4dfb4a4d7e)
}

var fileDescriptor_e0cd8e4dfb4a4d7e = []byte{
	// 258 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0x41, 0x4b, 0x03, 0x31,
	0x10, 0x85, 0xa9, 0xda, 0xd5, 0xa6, 0x7a, 0x09, 0x52, 0x02, 0x22, 0x8a, 0x5e, 0x44, 0xd8, 0x2d,
	0xc5, 0xbb, 0x48, 0xa1, 0x57, 0x15, 0x05, 0x0f, 0x5e, 0x42, 0x36, 0x4e, 0xb7, 0x81, 0xdd, 0xcc,
	0x92, 0xcc, 0xae, 0xbf, 0xd9, 0x7f, 0x21, 0x99, 0xb6, 0xae, 0xb7, 0xbc, 0xef, 0x7d, 0x0c, 0xe4,
	0x89, 0xfb, 0xc6, 0x78, 0xb7, 0x86, 0x48, 0x45, 0xbf, 0x98, 0x43, 0x24, 0xb3, 0x06, 0x22, 0xd0,
	0xad, 0x6b, 0xa1, 0x76, 0x1e, 0x34, 0xf4, 0xe0, 0xa9, 0x68, 0x03, 0x12, 0xca, 0xe9, 0x3f, 0xf7,
	0xe6, 0x67, 0x24, 0x66, 0xab, 0xbd, 0xff, 0xba, 0xd3, 0x57, 0xc9, 0x96, 0xb7, 0xe2, 0xac, 0xec,
	0x5c, 0xfd, 0xa5, 0x7b, 0x08, 0xd1, 0xa1, 0x57, 0xa3, 0xeb, 0xd1, 0xdd, 0xe4, 0xed, 0x94, 0xe1,
	0xc7, 0x96, 0xc9, 0x2b, 0x31, 0x0d, 0xd0, 0xa2, 0x8e, 0xd8, 0x05, 0x0b, 0xea, 0x80, 0x15, 0x91,
	0xd0, 0x3b, 0x13, 0x79, 0x29, 0x38, 0x69, 0xfc, 0xf6, 0x10, 0xd4, 0x21, 0xf7, 0x93, 0x44, 0x5e,
	0x12, 0x90, 0x17, 0x82, 0x83, 0xf6, 0xa6, 0x01, 0x75, 0xc4, 0xed, 0x49, 0x02, 0xcf, 0xa6, 0x81,
	0xbf, 0xe3, 0x65, 0x30, 0xde, 0x6e, 0xd4, 0x78, 0x38, 0xbe, 0x64, 0x22, 0x67, 0x22, 0x8b, 0x64,
	0xa8, 0x8b, 0x2a, 0xe3, 0x6e, 0x97, 0xe4, 0xb9, 0x18, 0xf3, 0x8f, 0xd5, 0x31, 0xe3, 0x6d, 0x58,
	0x3e, 0x7d, 0x3e, 0x56, 0x8e, 0x36, 0x5d, 0x59, 0x58, 0x6c, 0x86, 0x95, 0x86, 0x57, 0x6e, 0x5d,
	0x6e, 0xd1, 0x53, 0x30, 0x96, 0x62, 0x5e, 0x61, 0x6d, 0x7c, 0x35, 0xdf, 0xaf, 0xa5, 0xfb, 0x45,
	0x99, 0xf1, 0x82, 0x0f, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x35, 0x0c, 0x38, 0x3e, 0x6f, 0x01,
	0x00, 0x00,
}
