// Code generated by protoc-gen-go. DO NOT EDIT.
// source: manifest.v1/estafette_release_trigger.proto

package manifest_v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EstafetteReleaseTrigger struct {
	Event                string   `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	Status               string   `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Target               string   `protobuf:"bytes,4,opt,name=target,proto3" json:"target,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EstafetteReleaseTrigger) Reset()         { *m = EstafetteReleaseTrigger{} }
func (m *EstafetteReleaseTrigger) String() string { return proto.CompactTextString(m) }
func (*EstafetteReleaseTrigger) ProtoMessage()    {}
func (*EstafetteReleaseTrigger) Descriptor() ([]byte, []int) {
	return fileDescriptor_546607dca40f86bd, []int{0}
}

func (m *EstafetteReleaseTrigger) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EstafetteReleaseTrigger.Unmarshal(m, b)
}
func (m *EstafetteReleaseTrigger) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EstafetteReleaseTrigger.Marshal(b, m, deterministic)
}
func (m *EstafetteReleaseTrigger) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EstafetteReleaseTrigger.Merge(m, src)
}
func (m *EstafetteReleaseTrigger) XXX_Size() int {
	return xxx_messageInfo_EstafetteReleaseTrigger.Size(m)
}
func (m *EstafetteReleaseTrigger) XXX_DiscardUnknown() {
	xxx_messageInfo_EstafetteReleaseTrigger.DiscardUnknown(m)
}

var xxx_messageInfo_EstafetteReleaseTrigger proto.InternalMessageInfo

func (m *EstafetteReleaseTrigger) GetEvent() string {
	if m != nil {
		return m.Event
	}
	return ""
}

func (m *EstafetteReleaseTrigger) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *EstafetteReleaseTrigger) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *EstafetteReleaseTrigger) GetTarget() string {
	if m != nil {
		return m.Target
	}
	return ""
}

func init() {
	proto.RegisterType((*EstafetteReleaseTrigger)(nil), "manifest.v1.EstafetteReleaseTrigger")
}

func init() {
	proto.RegisterFile("manifest.v1/estafette_release_trigger.proto", fileDescriptor_546607dca40f86bd)
}

var fileDescriptor_546607dca40f86bd = []byte{
	// 190 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0xcf, 0x41, 0x8b, 0xc2, 0x30,
	0x10, 0x05, 0x60, 0xba, 0xdb, 0x2d, 0x6c, 0xf6, 0x16, 0x16, 0xcd, 0x51, 0x3c, 0x09, 0xd2, 0x96,
	0xe2, 0x5d, 0x44, 0xf0, 0x0f, 0x14, 0x4f, 0x5e, 0xca, 0x34, 0x4c, 0x63, 0xa0, 0x4d, 0x24, 0x99,
	0xf6, 0xf7, 0x8b, 0x89, 0xa5, 0xde, 0xe6, 0x3d, 0xbe, 0xc3, 0x1b, 0xb6, 0x1f, 0xc0, 0xe8, 0x0e,
	0x3d, 0x15, 0x53, 0x55, 0xa2, 0x27, 0xe8, 0x90, 0x08, 0x1b, 0x87, 0x3d, 0x82, 0xc7, 0x86, 0x9c,
	0x56, 0x0a, 0x5d, 0xf1, 0x70, 0x96, 0x2c, 0xff, 0xfb, 0xc0, 0x5b, 0xcf, 0xd6, 0x97, 0xd9, 0xd7,
	0x91, 0x5f, 0xa3, 0xe6, 0xff, 0xec, 0x07, 0x27, 0x34, 0x24, 0x92, 0x4d, 0xb2, 0xfb, 0xad, 0x63,
	0xe0, 0x2b, 0x96, 0x79, 0x02, 0x1a, 0xbd, 0xf8, 0x0a, 0xf5, 0x3b, 0x71, 0xce, 0x52, 0x03, 0x03,
	0x8a, 0xef, 0xd0, 0x86, 0xfb, 0x65, 0x09, 0x9c, 0x42, 0x12, 0x69, 0xb4, 0x31, 0x9d, 0x4f, 0xb7,
	0xa3, 0xd2, 0x74, 0x1f, 0xdb, 0x42, 0xda, 0x61, 0xd9, 0xbb, 0x5c, 0xb9, 0xd4, 0xb9, 0xb4, 0x86,
	0x1c, 0x48, 0xf2, 0xb9, 0xb2, 0x3d, 0x18, 0x55, 0xce, 0xb3, 0x9b, 0xa9, 0x6a, 0xb3, 0xf0, 0xca,
	0xe1, 0x19, 0x00, 0x00, 0xff, 0xff, 0x40, 0x6c, 0xc7, 0xfa, 0xf9, 0x00, 0x00, 0x00,
}
