// Code generated by protoc-gen-go. DO NOT EDIT.
// source: manifest.v1/estafette_builder.proto

package manifest_v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EstafetteBuilder struct {
	Track                string   `protobuf:"bytes,1,opt,name=track,proto3" json:"track,omitempty"`
	OperatingSystem      string   `protobuf:"bytes,2,opt,name=operating_system,json=operatingSystem,proto3" json:"operating_system,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EstafetteBuilder) Reset()         { *m = EstafetteBuilder{} }
func (m *EstafetteBuilder) String() string { return proto.CompactTextString(m) }
func (*EstafetteBuilder) ProtoMessage()    {}
func (*EstafetteBuilder) Descriptor() ([]byte, []int) {
	return fileDescriptor_de64690c24b9c18f, []int{0}
}

func (m *EstafetteBuilder) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EstafetteBuilder.Unmarshal(m, b)
}
func (m *EstafetteBuilder) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EstafetteBuilder.Marshal(b, m, deterministic)
}
func (m *EstafetteBuilder) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EstafetteBuilder.Merge(m, src)
}
func (m *EstafetteBuilder) XXX_Size() int {
	return xxx_messageInfo_EstafetteBuilder.Size(m)
}
func (m *EstafetteBuilder) XXX_DiscardUnknown() {
	xxx_messageInfo_EstafetteBuilder.DiscardUnknown(m)
}

var xxx_messageInfo_EstafetteBuilder proto.InternalMessageInfo

func (m *EstafetteBuilder) GetTrack() string {
	if m != nil {
		return m.Track
	}
	return ""
}

func (m *EstafetteBuilder) GetOperatingSystem() string {
	if m != nil {
		return m.OperatingSystem
	}
	return ""
}

func init() {
	proto.RegisterType((*EstafetteBuilder)(nil), "manifest.v1.EstafetteBuilder")
}

func init() {
	proto.RegisterFile("manifest.v1/estafette_builder.proto", fileDescriptor_de64690c24b9c18f)
}

var fileDescriptor_de64690c24b9c18f = []byte{
	// 170 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0xce, 0x4d, 0xcc, 0xcb,
	0x4c, 0x4b, 0x2d, 0x2e, 0xd1, 0x2b, 0x33, 0xd4, 0x4f, 0x2d, 0x2e, 0x49, 0x4c, 0x4b, 0x2d, 0x29,
	0x49, 0x8d, 0x4f, 0x2a, 0xcd, 0xcc, 0x49, 0x49, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17,
	0xe2, 0x46, 0x52, 0xa4, 0x14, 0xcc, 0x25, 0xe0, 0x0a, 0x53, 0xe7, 0x04, 0x51, 0x26, 0x24, 0xc2,
	0xc5, 0x5a, 0x52, 0x94, 0x98, 0x9c, 0x2d, 0xc1, 0xa8, 0xc0, 0xa8, 0xc1, 0x19, 0x04, 0xe1, 0x08,
	0x69, 0x72, 0x09, 0xe4, 0x17, 0xa4, 0x16, 0x25, 0x96, 0x64, 0xe6, 0xa5, 0xc7, 0x17, 0x57, 0x16,
	0x97, 0xa4, 0xe6, 0x4a, 0x30, 0x81, 0x15, 0xf0, 0xc3, 0xc5, 0x83, 0xc1, 0xc2, 0x4e, 0x0e, 0x51,
	0x76, 0xe9, 0x99, 0x25, 0x19, 0xa5, 0x49, 0x7a, 0xc9, 0xf9, 0xb9, 0x08, 0x77, 0x20, 0x58, 0xba,
	0xc9, 0x99, 0xba, 0xc9, 0xf9, 0x79, 0x20, 0x83, 0x4b, 0x8a, 0x75, 0xd3, 0xf3, 0x73, 0x12, 0xf3,
	0xd2, 0xf5, 0x61, 0xce, 0x8a, 0x2f, 0x33, 0x4c, 0x62, 0x03, 0x3b, 0xd5, 0x18, 0x10, 0x00, 0x00,
	0xff, 0xff, 0x85, 0xd9, 0x77, 0x0f, 0xd1, 0x00, 0x00, 0x00,
}
