// Code generated by protoc-gen-go. DO NOT EDIT.
// source: manifest.v1/estafette_pipeline_trigger.proto

package manifest_v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EstafettePipelineTrigger struct {
	Event                string   `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	Status               string   `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Branch               string   `protobuf:"bytes,4,opt,name=branch,proto3" json:"branch,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EstafettePipelineTrigger) Reset()         { *m = EstafettePipelineTrigger{} }
func (m *EstafettePipelineTrigger) String() string { return proto.CompactTextString(m) }
func (*EstafettePipelineTrigger) ProtoMessage()    {}
func (*EstafettePipelineTrigger) Descriptor() ([]byte, []int) {
	return fileDescriptor_dbd39a53672b20d9, []int{0}
}

func (m *EstafettePipelineTrigger) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EstafettePipelineTrigger.Unmarshal(m, b)
}
func (m *EstafettePipelineTrigger) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EstafettePipelineTrigger.Marshal(b, m, deterministic)
}
func (m *EstafettePipelineTrigger) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EstafettePipelineTrigger.Merge(m, src)
}
func (m *EstafettePipelineTrigger) XXX_Size() int {
	return xxx_messageInfo_EstafettePipelineTrigger.Size(m)
}
func (m *EstafettePipelineTrigger) XXX_DiscardUnknown() {
	xxx_messageInfo_EstafettePipelineTrigger.DiscardUnknown(m)
}

var xxx_messageInfo_EstafettePipelineTrigger proto.InternalMessageInfo

func (m *EstafettePipelineTrigger) GetEvent() string {
	if m != nil {
		return m.Event
	}
	return ""
}

func (m *EstafettePipelineTrigger) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *EstafettePipelineTrigger) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *EstafettePipelineTrigger) GetBranch() string {
	if m != nil {
		return m.Branch
	}
	return ""
}

func init() {
	proto.RegisterType((*EstafettePipelineTrigger)(nil), "manifest.v1.EstafettePipelineTrigger")
}

func init() {
	proto.RegisterFile("manifest.v1/estafette_pipeline_trigger.proto", fileDescriptor_dbd39a53672b20d9)
}

var fileDescriptor_dbd39a53672b20d9 = []byte{
	// 210 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x8f, 0x31, 0x6b, 0xc3, 0x30,
	0x10, 0x85, 0xb1, 0xeb, 0x1a, 0xaa, 0x6e, 0xa2, 0x14, 0x8d, 0xa5, 0x53, 0x87, 0x5a, 0xc6, 0x74,
	0xef, 0xd0, 0xd2, 0xa1, 0x43, 0xa1, 0x84, 0x90, 0x21, 0x19, 0x8c, 0x2c, 0xce, 0xb2, 0xc0, 0x96,
	0x8c, 0x74, 0xf6, 0x8f, 0xca, 0xaf, 0x0c, 0x91, 0x6c, 0x9c, 0xed, 0xde, 0xe3, 0x3b, 0xf8, 0x1e,
	0x79, 0x1f, 0x84, 0xd1, 0x2d, 0x78, 0xe4, 0x73, 0x55, 0x82, 0x47, 0xd1, 0x02, 0x22, 0xd4, 0xa3,
	0x1e, 0xa1, 0xd7, 0x06, 0x6a, 0x74, 0x5a, 0x29, 0x70, 0x7c, 0x74, 0x16, 0x2d, 0x7d, 0xbc, 0xa1,
	0x5f, 0x91, 0xb0, 0x9f, 0xf5, 0xe1, 0x7f, 0xe1, 0xf7, 0x11, 0xa7, 0x4f, 0xe4, 0x1e, 0x66, 0x30,
	0xc8, 0x92, 0x97, 0xe4, 0xed, 0x61, 0x17, 0x03, 0x7d, 0x26, 0xb9, 0x47, 0x81, 0x93, 0x67, 0x69,
	0xa8, 0x97, 0x44, 0x29, 0xc9, 0x8c, 0x18, 0x80, 0xdd, 0x85, 0x36, 0xdc, 0x57, 0xb6, 0x71, 0xc2,
	0xc8, 0x8e, 0x65, 0x91, 0x8d, 0xe9, 0xeb, 0x74, 0xfc, 0x54, 0x1a, 0xbb, 0xa9, 0xe1, 0xd2, 0x0e,
	0x9b, 0xf1, 0x76, 0x15, 0x52, 0x17, 0xd2, 0x1a, 0x74, 0x42, 0xa2, 0x2f, 0x94, 0xed, 0x85, 0x51,
	0xe5, 0xea, 0x5d, 0xcf, 0xd5, 0x39, 0xdd, 0xb4, 0xf9, 0xf7, 0x2f, 0xff, 0x5b, 0x27, 0x1d, 0xaa,
	0x26, 0x0f, 0x33, 0x3f, 0x2e, 0x01, 0x00, 0x00, 0xff, 0xff, 0x7f, 0xad, 0xd7, 0x23, 0x16, 0x01,
	0x00, 0x00,
}
