// Code generated by protoc-gen-go. DO NOT EDIT.
// source: manifest.v1/estafette_cron_trigger.proto

package manifest_v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EstafetteCronTrigger struct {
	Schedule             string   `protobuf:"bytes,1,opt,name=schedule,proto3" json:"schedule,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EstafetteCronTrigger) Reset()         { *m = EstafetteCronTrigger{} }
func (m *EstafetteCronTrigger) String() string { return proto.CompactTextString(m) }
func (*EstafetteCronTrigger) ProtoMessage()    {}
func (*EstafetteCronTrigger) Descriptor() ([]byte, []int) {
	return fileDescriptor_99113576a89783bf, []int{0}
}

func (m *EstafetteCronTrigger) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EstafetteCronTrigger.Unmarshal(m, b)
}
func (m *EstafetteCronTrigger) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EstafetteCronTrigger.Marshal(b, m, deterministic)
}
func (m *EstafetteCronTrigger) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EstafetteCronTrigger.Merge(m, src)
}
func (m *EstafetteCronTrigger) XXX_Size() int {
	return xxx_messageInfo_EstafetteCronTrigger.Size(m)
}
func (m *EstafetteCronTrigger) XXX_DiscardUnknown() {
	xxx_messageInfo_EstafetteCronTrigger.DiscardUnknown(m)
}

var xxx_messageInfo_EstafetteCronTrigger proto.InternalMessageInfo

func (m *EstafetteCronTrigger) GetSchedule() string {
	if m != nil {
		return m.Schedule
	}
	return ""
}

func init() {
	proto.RegisterType((*EstafetteCronTrigger)(nil), "manifest.v1.EstafetteCronTrigger")
}

func init() {
	proto.RegisterFile("manifest.v1/estafette_cron_trigger.proto", fileDescriptor_99113576a89783bf)
}

var fileDescriptor_99113576a89783bf = []byte{
	// 154 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xd2, 0xc8, 0x4d, 0xcc, 0xcb,
	0x4c, 0x4b, 0x2d, 0x2e, 0xd1, 0x2b, 0x33, 0xd4, 0x4f, 0x2d, 0x2e, 0x49, 0x4c, 0x4b, 0x2d, 0x29,
	0x49, 0x8d, 0x4f, 0x2e, 0xca, 0xcf, 0x8b, 0x2f, 0x29, 0xca, 0x4c, 0x4f, 0x4f, 0x2d, 0xd2, 0x2b,
	0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x46, 0x52, 0xa9, 0x64, 0xc4, 0x25, 0xe2, 0x0a, 0x53, 0xec,
	0x5c, 0x94, 0x9f, 0x17, 0x02, 0x51, 0x2a, 0x24, 0xc5, 0xc5, 0x51, 0x9c, 0x9c, 0x91, 0x9a, 0x52,
	0x9a, 0x93, 0x2a, 0xc1, 0xa8, 0xc0, 0xa8, 0xc1, 0x19, 0x04, 0xe7, 0x3b, 0x39, 0x44, 0xd9, 0xa5,
	0x67, 0x96, 0x64, 0x94, 0x26, 0xe9, 0x25, 0xe7, 0xe7, 0x22, 0xec, 0x42, 0xb0, 0x74, 0x93, 0x33,
	0x75, 0x93, 0xf3, 0xf3, 0x4a, 0x8a, 0x12, 0x93, 0x4b, 0x8a, 0x75, 0xd3, 0xf3, 0x73, 0x12, 0xf3,
	0xd2, 0xf5, 0x61, 0xb6, 0xc6, 0x97, 0x19, 0x26, 0xb1, 0x81, 0x5d, 0x62, 0x0c, 0x08, 0x00, 0x00,
	0xff, 0xff, 0x8b, 0x76, 0x89, 0x3a, 0xb5, 0x00, 0x00, 0x00,
}
