// Code generated by protoc-gen-go. DO NOT EDIT.
// source: manifest.v1/estafette_git_trigger.proto

package manifest_v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EstafetteGitTrigger struct {
	Event                string   `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	Repository           string   `protobuf:"bytes,2,opt,name=repository,proto3" json:"repository,omitempty"`
	Branch               string   `protobuf:"bytes,3,opt,name=branch,proto3" json:"branch,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EstafetteGitTrigger) Reset()         { *m = EstafetteGitTrigger{} }
func (m *EstafetteGitTrigger) String() string { return proto.CompactTextString(m) }
func (*EstafetteGitTrigger) ProtoMessage()    {}
func (*EstafetteGitTrigger) Descriptor() ([]byte, []int) {
	return fileDescriptor_006daccc9169db0a, []int{0}
}

func (m *EstafetteGitTrigger) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EstafetteGitTrigger.Unmarshal(m, b)
}
func (m *EstafetteGitTrigger) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EstafetteGitTrigger.Marshal(b, m, deterministic)
}
func (m *EstafetteGitTrigger) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EstafetteGitTrigger.Merge(m, src)
}
func (m *EstafetteGitTrigger) XXX_Size() int {
	return xxx_messageInfo_EstafetteGitTrigger.Size(m)
}
func (m *EstafetteGitTrigger) XXX_DiscardUnknown() {
	xxx_messageInfo_EstafetteGitTrigger.DiscardUnknown(m)
}

var xxx_messageInfo_EstafetteGitTrigger proto.InternalMessageInfo

func (m *EstafetteGitTrigger) GetEvent() string {
	if m != nil {
		return m.Event
	}
	return ""
}

func (m *EstafetteGitTrigger) GetRepository() string {
	if m != nil {
		return m.Repository
	}
	return ""
}

func (m *EstafetteGitTrigger) GetBranch() string {
	if m != nil {
		return m.Branch
	}
	return ""
}

func init() {
	proto.RegisterType((*EstafetteGitTrigger)(nil), "manifest.v1.EstafetteGitTrigger")
}

func init() {
	proto.RegisterFile("manifest.v1/estafette_git_trigger.proto", fileDescriptor_006daccc9169db0a)
}

var fileDescriptor_006daccc9169db0a = []byte{
	// 182 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x8e, 0xc1, 0xcb, 0x82, 0x40,
	0x10, 0x47, 0xf1, 0xfb, 0x48, 0x68, 0xbb, 0x6d, 0x11, 0x9e, 0x22, 0xba, 0xd4, 0x45, 0x45, 0xba,
	0x47, 0x04, 0xd1, 0x3d, 0x3a, 0x75, 0x91, 0x75, 0x19, 0xd7, 0x85, 0xdc, 0x91, 0xd9, 0x49, 0xe8,
	0xbf, 0x0f, 0x34, 0xd1, 0xdb, 0xfc, 0xe6, 0xbd, 0xc3, 0x13, 0xfb, 0x5a, 0x39, 0x5b, 0x82, 0xe7,
	0xa4, 0xcd, 0x52, 0xf0, 0xac, 0x4a, 0x60, 0x86, 0xdc, 0x58, 0xce, 0x99, 0xac, 0x31, 0x40, 0x49,
	0x43, 0xc8, 0x28, 0x17, 0x13, 0x71, 0xa7, 0xc5, 0xf2, 0x3a, 0xb8, 0x37, 0xcb, 0x8f, 0xde, 0x94,
	0x2b, 0x31, 0x83, 0x16, 0x1c, 0x47, 0xc1, 0x36, 0x38, 0xcc, 0xef, 0xfd, 0x90, 0x1b, 0x21, 0x08,
	0x1a, 0xf4, 0x96, 0x91, 0x3e, 0xd1, 0x5f, 0x87, 0x26, 0x1f, 0xb9, 0x16, 0x61, 0x41, 0xca, 0xe9,
	0x2a, 0xfa, 0xef, 0xd8, 0x6f, 0x5d, 0xce, 0xcf, 0x93, 0xb1, 0x5c, 0xbd, 0x8b, 0x44, 0x63, 0x3d,
	0xb6, 0x8d, 0x57, 0xac, 0x6d, 0xac, 0xd1, 0x31, 0x29, 0xcd, 0x3e, 0x36, 0xf8, 0x52, 0xce, 0xa4,
	0x43, 0x66, 0xde, 0x66, 0x45, 0xd8, 0xa5, 0x1f, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x8e, 0x41,
	0xc7, 0xed, 0xe5, 0x00, 0x00, 0x00,
}
