// Code generated by protoc-gen-go. DO NOT EDIT.
// source: manifest.v1/estafette_trigger_release_action.proto

package manifest_v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EstafetteTriggerReleaseAction struct {
	Target               string   `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	Action               string   `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	Version              string   `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EstafetteTriggerReleaseAction) Reset()         { *m = EstafetteTriggerReleaseAction{} }
func (m *EstafetteTriggerReleaseAction) String() string { return proto.CompactTextString(m) }
func (*EstafetteTriggerReleaseAction) ProtoMessage()    {}
func (*EstafetteTriggerReleaseAction) Descriptor() ([]byte, []int) {
	return fileDescriptor_87fa1de4dd662d92, []int{0}
}

func (m *EstafetteTriggerReleaseAction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EstafetteTriggerReleaseAction.Unmarshal(m, b)
}
func (m *EstafetteTriggerReleaseAction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EstafetteTriggerReleaseAction.Marshal(b, m, deterministic)
}
func (m *EstafetteTriggerReleaseAction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EstafetteTriggerReleaseAction.Merge(m, src)
}
func (m *EstafetteTriggerReleaseAction) XXX_Size() int {
	return xxx_messageInfo_EstafetteTriggerReleaseAction.Size(m)
}
func (m *EstafetteTriggerReleaseAction) XXX_DiscardUnknown() {
	xxx_messageInfo_EstafetteTriggerReleaseAction.DiscardUnknown(m)
}

var xxx_messageInfo_EstafetteTriggerReleaseAction proto.InternalMessageInfo

func (m *EstafetteTriggerReleaseAction) GetTarget() string {
	if m != nil {
		return m.Target
	}
	return ""
}

func (m *EstafetteTriggerReleaseAction) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

func (m *EstafetteTriggerReleaseAction) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func init() {
	proto.RegisterType((*EstafetteTriggerReleaseAction)(nil), "manifest.v1.EstafetteTriggerReleaseAction")
}

func init() {
	proto.RegisterFile("manifest.v1/estafette_trigger_release_action.proto", fileDescriptor_87fa1de4dd662d92)
}

var fileDescriptor_87fa1de4dd662d92 = []byte{
	// 212 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x8f, 0xb1, 0x4b, 0xc6, 0x30,
	0x10, 0xc5, 0xf9, 0x3e, 0xa1, 0x62, 0xdc, 0x3a, 0x48, 0x16, 0x41, 0x3a, 0xb9, 0xf4, 0x4a, 0x75,
	0x74, 0x52, 0x71, 0x70, 0x70, 0x29, 0xe2, 0xe0, 0x12, 0xd2, 0x70, 0x8d, 0x07, 0x6d, 0x23, 0xc9,
	0xd9, 0xc9, 0xbf, 0xc8, 0xbf, 0x52, 0xda, 0x7c, 0x69, 0xbb, 0xdd, 0xbb, 0xc7, 0xef, 0xf1, 0x9e,
	0xb8, 0x1b, 0xf4, 0x48, 0x1d, 0x06, 0x86, 0xa9, 0xae, 0x30, 0xb0, 0xee, 0x90, 0x19, 0x15, 0x7b,
	0xb2, 0x16, 0xbd, 0xf2, 0xd8, 0xa3, 0x0e, 0xa8, 0xb4, 0x61, 0x72, 0x23, 0x7c, 0x7b, 0xc7, 0x2e,
	0xbf, 0xdc, 0x31, 0x05, 0x89, 0xeb, 0x97, 0x84, 0xbd, 0x47, 0xaa, 0x89, 0xd0, 0xe3, 0xc2, 0xe4,
	0x57, 0x22, 0x63, 0xed, 0x2d, 0xb2, 0x3c, 0xdc, 0x1c, 0x6e, 0x2f, 0x9a, 0x93, 0x9a, 0xff, 0x31,
	0x55, 0x1e, 0xe3, 0x3f, 0xaa, 0x5c, 0x8a, 0xf3, 0x09, 0x7d, 0x98, 0x8d, 0xb3, 0xc5, 0x48, 0xf2,
	0xe9, 0x57, 0x14, 0xe4, 0x60, 0x2d, 0x09, 0x86, 0x62, 0xa1, 0x00, 0xbb, 0x42, 0x9f, 0x0f, 0x96,
	0xf8, 0xeb, 0xa7, 0x05, 0xe3, 0x86, 0x6d, 0xd0, 0x76, 0x95, 0x86, 0xca, 0x48, 0x95, 0xd6, 0xf5,
	0x7a, 0xb4, 0x55, 0x82, 0xd5, 0x54, 0xff, 0x1d, 0xe5, 0x3a, 0x06, 0x9e, 0x5f, 0xe1, 0x2d, 0xe5,
	0x7e, 0xd4, 0x6d, 0xb6, 0x50, 0xf7, 0xff, 0x01, 0x00, 0x00, 0xff, 0xff, 0x79, 0xfc, 0xea, 0x9c,
	0x32, 0x01, 0x00, 0x00,
}
