// Code generated by protoc-gen-go. DO NOT EDIT.
// source: manifest.v1/estafette_release_event.proto

package manifest_v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EstafetteReleaseEvent struct {
	ReleaseVersion       string   `protobuf:"bytes,1,opt,name=release_version,json=releaseVersion,proto3" json:"release_version,omitempty"`
	RepoSource           string   `protobuf:"bytes,2,opt,name=repo_source,json=repoSource,proto3" json:"repo_source,omitempty"`
	RepoOwner            string   `protobuf:"bytes,3,opt,name=repo_owner,json=repoOwner,proto3" json:"repo_owner,omitempty"`
	RepoName             string   `protobuf:"bytes,4,opt,name=repo_name,json=repoName,proto3" json:"repo_name,omitempty"`
	Target               string   `protobuf:"bytes,5,opt,name=target,proto3" json:"target,omitempty"`
	Status               string   `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	Event                string   `protobuf:"bytes,7,opt,name=event,proto3" json:"event,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EstafetteReleaseEvent) Reset()         { *m = EstafetteReleaseEvent{} }
func (m *EstafetteReleaseEvent) String() string { return proto.CompactTextString(m) }
func (*EstafetteReleaseEvent) ProtoMessage()    {}
func (*EstafetteReleaseEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_4331d3b6363a4047, []int{0}
}

func (m *EstafetteReleaseEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EstafetteReleaseEvent.Unmarshal(m, b)
}
func (m *EstafetteReleaseEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EstafetteReleaseEvent.Marshal(b, m, deterministic)
}
func (m *EstafetteReleaseEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EstafetteReleaseEvent.Merge(m, src)
}
func (m *EstafetteReleaseEvent) XXX_Size() int {
	return xxx_messageInfo_EstafetteReleaseEvent.Size(m)
}
func (m *EstafetteReleaseEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_EstafetteReleaseEvent.DiscardUnknown(m)
}

var xxx_messageInfo_EstafetteReleaseEvent proto.InternalMessageInfo

func (m *EstafetteReleaseEvent) GetReleaseVersion() string {
	if m != nil {
		return m.ReleaseVersion
	}
	return ""
}

func (m *EstafetteReleaseEvent) GetRepoSource() string {
	if m != nil {
		return m.RepoSource
	}
	return ""
}

func (m *EstafetteReleaseEvent) GetRepoOwner() string {
	if m != nil {
		return m.RepoOwner
	}
	return ""
}

func (m *EstafetteReleaseEvent) GetRepoName() string {
	if m != nil {
		return m.RepoName
	}
	return ""
}

func (m *EstafetteReleaseEvent) GetTarget() string {
	if m != nil {
		return m.Target
	}
	return ""
}

func (m *EstafetteReleaseEvent) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *EstafetteReleaseEvent) GetEvent() string {
	if m != nil {
		return m.Event
	}
	return ""
}

func init() {
	proto.RegisterType((*EstafetteReleaseEvent)(nil), "manifest.v1.EstafetteReleaseEvent")
}

func init() {
	proto.RegisterFile("manifest.v1/estafette_release_event.proto", fileDescriptor_4331d3b6363a4047)
}

var fileDescriptor_4331d3b6363a4047 = []byte{
	// 251 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0x41, 0x4b, 0x03, 0x31,
	0x10, 0x85, 0xa9, 0xda, 0xd5, 0xa6, 0xa0, 0x10, 0x54, 0x02, 0x22, 0x8a, 0x17, 0xf5, 0xb0, 0x5b,
	0x8a, 0x77, 0x11, 0xa1, 0x57, 0x85, 0x0a, 0x1e, 0xbc, 0x84, 0x69, 0x98, 0xae, 0x0b, 0xdd, 0x4c,
	0x49, 0x66, 0xd7, 0x1f, 0xec, 0x1f, 0x91, 0x4c, 0xba, 0xd4, 0x5b, 0xde, 0xf7, 0xbe, 0x1c, 0xe6,
	0xa9, 0xc7, 0x16, 0x7c, 0xb3, 0xc6, 0xc8, 0x55, 0x3f, 0x9f, 0x61, 0x64, 0x58, 0x23, 0x33, 0xda,
	0x80, 0x1b, 0x84, 0x88, 0x16, 0x7b, 0xf4, 0x5c, 0x6d, 0x03, 0x31, 0xe9, 0xe9, 0x3f, 0xf5, 0xee,
	0x77, 0xa4, 0x2e, 0x16, 0x83, 0xbe, 0xcc, 0xf6, 0x22, 0xc9, 0xfa, 0x5e, 0x9d, 0x0d, 0xbf, 0x7b,
	0x0c, 0xb1, 0x21, 0x6f, 0x46, 0xb7, 0xa3, 0x87, 0xc9, 0xf2, 0x74, 0x87, 0x3f, 0x33, 0xd5, 0x37,
	0x6a, 0x1a, 0x70, 0x4b, 0x36, 0x52, 0x17, 0x1c, 0x9a, 0x03, 0x91, 0x54, 0x42, 0x1f, 0x42, 0xf4,
	0xb5, 0x92, 0x64, 0xe9, 0xc7, 0x63, 0x30, 0x87, 0xd2, 0x4f, 0x12, 0x79, 0x4f, 0x40, 0x5f, 0x29,
	0x09, 0xd6, 0x43, 0x8b, 0xe6, 0x48, 0xda, 0x93, 0x04, 0xde, 0xa0, 0x45, 0x7d, 0xa9, 0x0a, 0x86,
	0x50, 0x23, 0x9b, 0xb1, 0x34, 0xbb, 0x94, 0x78, 0x64, 0xe0, 0x2e, 0x9a, 0x22, 0xf3, 0x9c, 0xf4,
	0xb9, 0x1a, 0xcb, 0xad, 0xe6, 0x58, 0x70, 0x0e, 0xaf, 0x2f, 0x5f, 0xcf, 0x75, 0xc3, 0xdf, 0xdd,
	0xaa, 0x72, 0xd4, 0xee, 0xe7, 0xd9, 0xbf, 0x4a, 0xd7, 0x94, 0x8e, 0x3c, 0x07, 0x70, 0x1c, 0xcb,
	0x9a, 0x36, 0xe0, 0xeb, 0xd9, 0xb0, 0x93, 0xed, 0xe7, 0xab, 0x42, 0xb6, 0x7b, 0xfa, 0x0b, 0x00,
	0x00, 0xff, 0xff, 0x33, 0x94, 0x25, 0x48, 0x68, 0x01, 0x00, 0x00,
}
